#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'extraLongFactorials' function below.
#
# The function accepts INTEGER n as parameter.
#

def extraLongFactorials(n):
    # Write your code here
    result = [1]

    for i in range(2, n + 1):
        carry = 0

        for j in range(len(result)):
            temp = result[j] * i + carry
            result[j] = temp % 10
            carry = temp // 10

        while carry:
            result.append(carry % 10)
            carry //= 10

    result_str = ''.join(map(str, result[::-1]))
    print(result_str)

if __name__ == '__main__':
    n = int(input().strip())

    extraLongFactorials(n)
